name: app_ui
description: App UI Component Library
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.0.0
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.3
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.0.3
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true
